---
title: "Movilidad Social Intergeneracional en México:Blog"
output: 
   html_document:
    df_print: paged
    rows.print: 5
    fig_width: 5 
    fig_height: 3

---

Genera gráficas asociadas al blog.

```{r setup, include=FALSE}

ipak <- function(pkg){
new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
sapply(pkg, require, character.only = TRUE)
}

# usage
packages <- c("ggplot2", "dplyr", "tidyr", 
              "survey", "janitor", "vtree",
              'questionr', 'purrr',
              'weights', 'pollster', 'plotly', 
              'knitr', 'htmltools')

ipak(packages)

opts_chunk$set(fig.width=6, 
               fig.height=4,
               echo=FALSE, 
               warning=FALSE, 
               message=FALSE, 
               fig.align = 'center', 
               results = 'asis',
               paged.print=TRUE)
```




```{r load data, echo=FALSE, warning=FALSE}
movilidad_social = read.csv('../data/clean_data.csv')
ms <- movilidad_social %>% drop_na(quintil_or)
```



```{r quintiles, echo=FALSE}

props_quintiles <- xtabs(factor~quintil_or+quintil_des, data=ms)
props_quintiles_df <- data.frame(props_quintiles)
props_quintiles_df <- props_quintiles_df[rep(row.names(props_quintiles_df), props_quintiles_df$Freq), 1:2]

prop_quintiles_movibilidad <-crosstab(
  ms,
  quintil_or,
  quintil_des,
  factor,
  remove = "",
  n = TRUE,
  pct_type = "row",
  format = "wide",
  unwt_n = FALSE
)
write.csv(prop_quintiles_movibilidad,
          "quintiles_movilidad.csv", 
          row.names = FALSE)

vtree(props_quintiles_df, 
      c("quintil_or",
        "quintil_des"), 
   fillcolor = c( quintil_or = "#83bdc0", 
                  quintil_des = "#f7c9b6"),
   labelvar = c(quintil_or="Quintil de Origen", 
                quintil_des ='Quintil de Destino'),
   horiz = TRUE,
   shownodelabels = FALSE,
   text=list(quintil_or=c("1"="\n*Quintil 1*", 
                    "2"="\n*Quintil 2*",
                    "3"="\n*Quintil 3*",
                    "4"="\n*Quintil 4*",
                    "5"="\n*Quintil 5*"),
             quintil_des=c("1"="\n*Quintil 1*", 
                    "2"="\n*Quintil 2*",
                    "3"="\n*Quintil 3*",
                    "4"="\n*Quintil 4*",
                    "5"="\n*Quintil 5*")),
   keep = list(quintil_or= c("1", "5")
               )
)
```



```{r edu padre hijo, echo=FALSE}
ms_edu_padre <- movilidad_social %>% drop_na(educ)
ms_edu_padre <- ms_edu_padre %>% drop_na(educ_padre)

props_quintiles_edu_padre <- xtabs(factor~educ + educ_padre, 
                                   data=ms_edu_padre)

props_quintiles_edu_df_padre <- data.frame(props_quintiles_edu_padre)
props_quintiles_edu_df_padre <- props_quintiles_edu_df_padre[rep(row.names(props_quintiles_edu_df_padre), props_quintiles_edu_df_padre$Freq), 1:2]

prop_quintiles_edu_padre <-crosstab(
  ms_edu_padre,
  educ,
  educ_padre,
  factor,
  remove = "",
  n = TRUE,
  pct_type = "row",
  format = "wide",
  unwt_n = FALSE
)


write.csv(prop_quintiles_edu_padre,
          "educacion_movilidad_padre.csv", 
          row.names = FALSE)

ggplot(ms_edu_padre, 
       aes(factor(educ), 
           factor(educ_padre)
           )
       ) + 
  geom_point(
    aes(
      size = factor
      ), 
    colour = "#83bdc0") + 
  theme_minimal() + 
  labs(x ="Educación del hijo (a)", 
       y ="Educación del Padre",
       title ="Movilidad Educacional Intergeneracional: Padre-Hijo(a)", 
       caption ="Fuente: Elaboración propio con base en la Encuesta ESRU-EMOVI 2017") + 
  scale_size_continuous(range=c(1,20), name='Conteo')  

```



```{r edu padre madre,echo=FALSE}

ms_edu_madre <- movilidad_social %>% drop_na(educ)
ms_edu_madre <- ms_edu_madre %>% drop_na(educ_madre)
props_quintiles_edu_madre <- xtabs(factor~educ + educ_madre, 
                                   data = ms_edu_madre)

props_quintiles_edu_df_madre <- data.frame(props_quintiles_edu_madre)
props_quintiles_edu_df_madre <- props_quintiles_edu_df_madre[rep(row.names(props_quintiles_edu_df_madre), props_quintiles_edu_df_madre$Freq), 1:2]

prop_quintiles_edu_madre <-crosstab(
  ms_edu_madre,
  educ,
  educ_madre,
  factor,
  remove = "",
  n = TRUE,
  pct_type = "row",
  format = "wide",
  unwt_n = FALSE
)

write.csv(prop_quintiles_edu_madre,
          "educacion_movilidad_madre.csv", 
          row.names = FALSE)

ggplot(ms_edu_madre, 
       aes(factor(educ), 
           factor(educ_madre)
           )
       ) + 
  geom_point(
    aes(
      size = factor
      ), 
    colour = "#c16648"
    ) + 
  theme_minimal() + 
  labs(x ="Educación del hijo(a)", 
       y ="Educación de la madre", 
       title ="Movilidad Educacional Intergeneracional: Madre-Hijo(a)", 
       caption ="Fuente: Elaboración propio con base en la Encuesta ESRU-EMOVI 2017") + 
  scale_size_continuous(range=c(1,20), name='Conteo') 
```






```{r movilidad mundial, echo=FALSE}
world_sm <- read.csv('../data/index_world_social_mobility.csv')

g1 <- subset(world_sm, 
             world_sm$Country == "Mexico")
g2 <- subset(world_sm, 
             world_sm$Country == "United States")
g3 <- subset(world_sm, 
             world_sm$Country == "Ivory Coast")
g4 <- subset(world_sm, 
             world_sm$Country == "Denmark")
g5 <- subset(world_sm,
             world_sm$Country == "Ecuador")


ggplot(world_sm, 
       aes(y = Index.Score, 
           x = Rank)
       ) +
   geom_point(alpha=1/3) +
   geom_point(data=g1, 
              color="#59981a")+
   geom_text(data=g1, 
             label="México", 
             vjust=1.5, 
             color="#59981a") +
   geom_point(data=g2, 
              color="#145da0") +
   geom_text(data=g2, 
             label="Estados Unidos", 
             vjust=2.5, 
             color='#145da0') +
   geom_point(data=g3, 
              color="#2e8bc0") +
   geom_text(data=g3, 
             label="Costa de Marfil", 
             vjust=1, 
             hjust=1.2, 
             color='#2e8bc0') +
   geom_point(data=g4, 
              color="#0c2d48") +
   geom_text(data=g4, 
             label="Dinamarca", 
             vjust=1, 
             hjust=-0.32, 
             color='#0c2d48') +
   geom_point(data=g5, 
              color="#5885af")+
   geom_text(data = g5, 
             label="Ecuador", 
             vjust = -1, 
             color='#5885af') +
   labs(title='Movilidad Social en el Mundo', 
        subtitle='Índice, 2020', 
        y='Índice', 
        x='Ranking', 
        caption='Elaboración propia con base en el índice de movilidad social creado por el Foro Económico Mundial.') +
  theme_minimal()


```
